---
# Test to validate ipsec settings ('bind_connection_to_interface' enabled) for following combination:
# - ipsec disabled for static and dynamic Dps tunnels
# - internet exit policy using IPsec based tunnels such as Zscaler.
wan_mode: cv-pathfinder
# Disabling underlay for tests
underlay_routing_protocol: none
# Prefer mechanism that avoids agent restart for kernel software forwarding of ecmp routes
wan_use_agent_env_var_for_kernel_software_forwarding_ecmp: false

type: wan_router

bgp_as: 65000

cv_pathfinder_regions:
  - name: AVD_Land_West_1
    id: 36
    description: AVD Region
    sites:
      - name: Site136
        id: 136
        location: Somewhere

bgp_peer_groups:
  wan_overlay_peers:
    password: "htm4AZe9mIQOO1uiMuGgYQ=="
    listen_range_prefixes:
      - 192.168.255.0/24

wan_route_servers:
  - hostname: cv-pathfinder-pathfinder
    vtep_ip: 10.10.10.10
    path_groups:
      - name: INET
        interfaces:
          - name: Ethernet1/1
            public_ip: 192.168.55.55

ipsec_settings:
  bind_connection_to_interface: true

wan_ipsec_profiles:
  control_plane:
    shared_key: ABCDEF1234567890
  data_plane:
    shared_key: ABCDEF1234567890666

wan_router:
  defaults:
    loopback_ipv4_pool: 192.168.42.0/24
    vtep_loopback_ipv4_pool: 192.168.255.0/24
    filter:
      always_include_vrfs_in_tenants: [TenantA]
  nodes:
    - name: cv-pathfinder-edge-no-ipsec-for-wan-path-group
      cv_pathfinder_region: AVD_Land_West_1
      cv_pathfinder_site: Site136
      id: 1
      l3_interfaces:
        - name: Ethernet1/1
          wan_carrier: ATT
          wan_circuit_id: 666
          ip_address: 192.168.1.105/31
          peer_ip: 192.168.1.104
          cv_pathfinder_internet_exit:
            policies:
              - name: ZSCALER-EXIT-POLICY-1
                tunnel_interface_numbers: 100-102
        - name: Ethernet1/2
          wan_carrier: ATT
          wan_circuit_id: 777
          ip_address: 192.168.2.205/31
          peer_ip: 192.168.2.204

wan_path_groups:
  - name: INET
    id: 101
    ipsec:
      static_peers: false
      dynamic_peers: false

wan_carriers:
  - name: ATT
    path_group: INET
    trusted: true

tenants:
  - name: TenantA
    vrfs:
      - name: default
        vrf_id: 1
      - name: PROD
        vrf_id: 42

wan_virtual_topologies:
  vrfs:
    - name: PROD
      wan_vni: 42
  policies:
    - name: DEFAULT-POLICY
      default_virtual_topology:
        drop_unmatched: true
      application_virtual_topologies:
        - application_profile: TEST
          path_groups:
            - names: [ INET ]
          internet_exit:
            policy: ZSCALER-EXIT-POLICY-1
          id: 42

application_classification:
  application_profiles:
    - name: TEST

cv_pathfinder_internet_exit_policies:
  - name: ZSCALER-EXIT-POLICY-1
    type: zscaler
    zscaler:
      domain_name: test.local
      ipsec_key_salt: THIS_SHOULD_BE_VAULTED

zscaler_endpoints:
  cloud_name: zscalerbeta
  device_location:
    city: Santa Clara, CA
    country: United States
  primary:
    city: Fremont, CA
    datacenter: FMT1
    country: United States
    region: us-west1
    latitude: 37
    longitude: -121
    ip_address: 192.168.121.108 # Not the correct address
