---
type: l3leaf

ptp_profiles:
  - profile: PROFILE-1

l3leaf:
  defaults:
    loopback_ipv4_pool: 10.254.1.0/27
    vtep_loopback_ipv4_pool: 10.254.11.0/27
    uplink_ipv4_pool: 10.254.12.0/24
    uplink_interfaces: ['Ethernet1']
    uplink_switches: ['failure-p2p-links-more-than-2-nodes']
    ptp:
      enabled: true
  nodes:
    - name: failure-ptp-profile-does-not-exist
      id: 1
      bgp_as: 65101
      mgmt_ip: 192.168.0.101/24
      uplink_switch_interfaces:
        - Ethernet1
      ptp:
        # The profile is applied on uplink or l3edge
        profile: THIS-PROFILE-DOES-NOT-EXIST

expected_error_message: >-
  PTP Profile 'THIS-PROFILE-DOES-NOT-EXIST' referenced under `ptp.profile` node variables
  does not exist in `ptp_profiles`.
